### ISSUE TITLE
Release 1.3.1 is not tagged as such in Docker Hub

### ISSUE THREAD

**Issue by MattBlissett** [asciidoctor/docker-asciidoctor#185]
The current release, 1.3.1, is available with the `latest` tag, but should ideally also be published with a `1.3.1` tag.

**Comment by dduportal** [comment]
Hello @MattBlissett , thanks for pointing this problem out, you are correct. Investigation in progress

**Comment by dduportal** [comment]
First thing first, I've managed to trigger a build recognized as a "tag" build: https://github.com/asciidoctor/docker-asciidoctor/actions/runs/605308677 . You should be able to have the image in the DockerHub in ~1 hour max.

The root cause is being investigated: it looks like that the build was not triggered as a "tag" one since the release was created from the draft's release. It sounds like that the previous tags (and the one triggered manually) were detected as such by GH Actions because these tags use to be pushed.

**Comment by dduportal** [comment]
- The build associated with the tag `1.3.1` succeeded and triggered a DockerHub rebuild: https://github.com/asciidoctor/docker-asciidoctor/runs/1993516212?check_suite_focus=true#step:6:143
- Root cause found: the PR #186 should fix the issue in the future 
- The builds for the tags `1`, `1.3` and `1.3.1` are pending on the DockerHub: almost there
