### ISSUE TITLE
kroki support? 

### ISSUE THREAD

**Issue by mskyaxl** [asciidoctor/docker-asciidoctor#191]
Hi, have you considered adding asciidoctor-kroki in this container?
https://github.com/Mogztter/asciidoctor-kroki

**Comment by mojavelinux** [comment]
I consider Kroki to be a partner community. Therefore, I think it's reasonable for it to be included in the container (assuming it doesn't cause too much weight). Though we are still facing the problem that this container is growing without bounds, so layers are something we really need as the number of projects people want to include increases.

**Comment by mojavelinux** [comment]
I would be supportive of adding Asciidoctor Kroki to the image, but not removing Asciidoctor Diagram. I don't want to create a situation where we put two projects in this ecosystem against each other. Asciidoctor Diagram and Kroki take different approaches to handling the work of diagram generation. The benefit of Asciidoctor Diagram is that it works completely locally. Asciidoctor Kroki offloads the work of generating the diagram to another server (which is why it's easier to support more diagram types without adding software). And since the provider is remote, adding the extension should be very lightweight.

If we get to a point where we offer several different images, I could see having one image that uses Asciidoctor Diagram and all its diagram tool dependencies and another image having Asciidoctor Kroki to keep the image more lean.

**Comment by dduportal** [comment]
Implemented in #226 and released in https://github.com/asciidoctor/docker-asciidoctor/releases/tag/1.13.0
