### ISSUE TITLE
unknown variable reference in PDF theme: $base-font-size

### ISSUE THREAD

**Issue by ts-sz** [asciidoctor/docker-asciidoctor#281]
Hi people,
when I use my local `asciidoctor-pdf` I can generate PDF without problems but when I try to use docker (last version) I have an error: `asciidoctor: WARNING: unknown variable reference in PDF theme: $base-font-size` and of course my pdf it's wrong.

Do you have any idea why?
https://asciinema.org/a/ybgFskrxRXwBo41OY3hmYBH1j

Local version
```
Asciidoctor PDF 1.6.2 using Asciidoctor 2.0.17 [https://asciidoctor.org]
Runtime Environment (ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

thanks

**Comment by mojavelinux** [comment]
It seems you are using an old version of the Docker image. It should report
Asciidoctor PDF 2.1.6. Can you pull again?

**Comment by ts-sz** [comment]
thanks @mojavelinux but i juste show you the last version of my local installation,
in the docker i use of course the last version:
```
bash-5.1# asciidoctor-pdf --version
Asciidoctor PDF 2.1.6 using Asciidoctor 2.0.17 [https://asciidoctor.org]
Runtime Environment (ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux-musl]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

```
Th probleme is then in my old version all work but not in new docker versions.

Thanks

**Comment by mojavelinux** [comment]
It seems like the problem you are having pertains to Asciidoctor PDF and not the Docker image. It would be best if you asked your question in the project chat at https://chat.asciidoctor.org instead. When you do, please share your theme file so that we are able to study it and detect what might be the problem.

**Comment by dduportal** [comment]
Hi @ts-sz , thanks for raising this issue.

You should follow @mojavelinux 's tip as you might run in an issue due to a 1.x -> 2.x major version change.

On short term, if you want to keep using a Docker image for this, we've been providing tags: use an older release of the image. For Asciidoctor PDF 1.6.2, searching the [releases](https://github.com/asciidoctor/docker-asciidoctor/releases) shows that [1.16.0](https://github.com/asciidoctor/docker-asciidoctor/releases/tag/1.16.0) is what you're searching for:

```shell
$ docker run --rm asciidoctor/docker-asciidoctor:1.16.0 asciidoctor-pdf --version
Asciidoctor PDF 1.6.2 using Asciidoctor 2.0.16 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-linux-musl]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```


I'm closing this issue as you have different solutions from now on, and it does not seem to be an issue on the Docker image.
Feel free to reopen with technical details if you found a technical problem. Thanks fro contributing by raising an issue!
