### ISSUE TITLE
Upgrade from ENV ASCIIDOCTOR_VERSION "1.5.5" to ENV ASCIIDOCTOR_VERSION "1.5.6.1"

### ISSUE THREAD

**Issue by patoi** [asciidoctor/docker-asciidoctor#43]

**Comment by dduportal** [comment]
Hello @patoi, thanks for your request!

Since we moved to Alpine Linux (#39) as docker base image, it raises a good question about the lifecycle of Asciidoctor version compared to the Alpine Linux lifecycle.

Currently, Alpine Linux provides:

* Asciidoctor 1.5.5 in Alpine Linux 3.6
* Asciidoctor 1.5.6.1 in Alpine Linux "Edge"

(source: https://pkgs.alpinelinux.org/packages?name=asciidoctor&branch=&repo=&arch=&maintainer= )

=> The maintainer of the package is Natanael Copa (@ncopa - https://github.com/ncopa ), one of the Alpine Linux creator/maintainer

=> We can expect Alpine Linux 3.7 released in ~17 days (source: https://bugs.alpinelinux.org/versions/119 ). It **should** embed the new asciidoctor package version.

=> Another solution would be to build (or install) our own asciidoctor without the alpine package to be able to get the "version" we want, for the price of a maintenance overhead. This is what the Docker "base" official images generally does. (Example for nginx: https://github.com/nginxinc/docker-nginx/blob/1d2e2ccae2f6e478f628f4091d8a5c36a122a157/mainline/stretch/Dockerfile )

=> We can also move away from Alpine Linux. I proposed #39 to gain some weight on the image, but this can be a solution in the future.


Hello @jirutka @mojavelinux @gscheibel : what would be your thought and advise on this pattern?

**Comment by jirutka** [comment]
> We can expect Alpine Linux 3.7 released in ~17 days…

Hm, I think that this release will be a bit later, we’re not in feature freeze state yet.

> We can also move away from Alpine Linux. 

That’s not really needed nor wise, it’d not solve this problem.

> …what would be your thought and advise on this pattern?

If you want the latest version, then I’d just install `asciidoctor` from Rubygems instead of Aports. It doesn’t have any native extensions in the dependency graph, so it’s not a problem.

**Comment by dduportal** [comment]
Thanks @jirutka !

I've opened #47 to implement this and upgrade the version to 1.5.6.1.

@patoi: you are welcome to help to review the PR 1.5.6.1, there is a docker image ready to pull from the docker hub to test.

**Comment by dduportal** [comment]
Pull Request #47 have been merged: I can close this issue.

Hello @patoi: you can get the latest version of the image with the following command:

```bash
docker pull asciidoctor/docker-asciidoctor
```

Please feel free to re-open this issue if you are not happy with the result!

Thank you for taking care of reporting this.

**Comment by patoi** [comment]
Thanks to all! It works fine. @dduportal @jirutka
